name: chandigarh
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  google_maps_flutter: ^2.2.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.3.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  intl: ^0.18.1
  fluttertoast: ^8.2.12
  loading_indicator: ^3.1.1
  dotted_border: ^2.0.0+3
  mime: ^1.0.4
  path: ^1.8.3
  http_parser: ^4.0.2
  flutter_image_compress: ^2.1.0
  image: ^4.1.3
  path_provider: ^2.1.1
  image_picker: ^1.0.0
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.0
  geocoding: ^2.0.0
  flutter_polyline_points: ^3.0.1
  app_settings: ^5.1.1
  translator: ^1.0.4+1
  supabase_flutter: ^2.10.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
